{{- if .Values.apiKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hipcortex.fullname" . }}-secrets
  labels:
    {{- include "hipcortex.labels" . | nindent 4 }}
type: Opaque
data:
  api-keys: {{ .Values.apiKeys | b64enc }}
{{- end }}
