apiVersion: v1
kind: Service
metadata:
  name: {{ include "hipcortex.fullname" . }}
  labels:
    {{- include "hipcortex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3030
      protocol: TCP
      name: http
  selector:
    {{- include "hipcortex.selectorLabels" . | nindent 4 }}
