"""HipCortex + LlamaIndex — persistent chat memory.
Generated by: hipcortex install
Docs: https://github.com/farmountain/HipCortex
"""
from hipcortex import HipCortexClient
from hipcortex.llamaindex_storage import HipCortexChatStore, HipCortexStorageContext

client = HipCortexClient("http://127.0.0.1:3030")

# Drop-in for SimpleChatStore
chat_store = HipCortexChatStore(client=client)

# Use with ChatMemoryBuffer:
# from llama_index.core.memory import ChatMemoryBuffer
# memory = ChatMemoryBuffer.from_defaults(
#     token_limit=3000,
#     chat_store=chat_store,
#     chat_store_key="user-42",
# )

# Storage context:
storage_context = HipCortexStorageContext.from_url("http://127.0.0.1:3030")

# Retrieve unified live beliefs for state and world predictions
beliefs = client.live_beliefs()
print("Unified Live Beliefs:", beliefs)
