"""HipCortex + CrewAI — memory tools for your crew.
Generated by: hipcortex install
Docs: https://github.com/farmountain/HipCortex
"""
from hipcortex import HipCortexClient
from hipcortex.adapters.crewai import (
    HipCortexRememberTool,
    HipCortexRecallTool,
    HipCortexForgetTool,
)

client = HipCortexClient("http://127.0.0.1:3030")

memory_tools = [
    HipCortexRememberTool(client=client, agent_id="my-crew"),
    HipCortexRecallTool(client=client, agent_id="my-crew"),
    HipCortexForgetTool(client=client, agent_id="my-crew"),
]

# Add to any CrewAI agent:
# from crewai import Agent
# researcher = Agent(
#     role="Researcher",
#     goal="Research and remember findings",
#     tools=memory_tools,
#     verbose=True,
# )
