"""HipCortex + AutoGen 0.4 — persistent memory for agents.
Generated by: hipcortex install
Docs: https://github.com/farmountain/HipCortex
"""
from hipcortex import HipCortexClient
from hipcortex.adapters.autogen import HipCortexAutoGenMemory

client = HipCortexClient("http://127.0.0.1:3030")
memory = HipCortexAutoGenMemory(client=client, agent_id="my-agent", top_k=10)

# AutoGen 0.4: pass memory=[memory] to AssistantAgent
# from autogen_agentchat.agents import AssistantAgent
# agent = AssistantAgent(
#     name="assistant",
#     model_client=...,
#     memory=[memory],
# )

# AutoGen 0.3 legacy hooks:
# agent.register_hook("process_message_before_send", memory.on_message_sent_v03)
# agent.register_hook("process_all_messages_before_reply", memory.on_messages_received_v03)

# Zero-config shortcut:
# client.remember("We decided to use PostgreSQL")
# memories = client.recall("database choice")
