"""HipCortex + LangChain — drop-in memory integration.
Generated by: hipcortex install
Docs: https://github.com/farmountain/HipCortex
"""
from hipcortex.langchain_memory import HipCortexMemory, AsyncHipCortexMemory

# Sync usage (drop-in for ConversationBufferMemory)
memory = HipCortexMemory(
    session_id="my-agent",
    url="http://127.0.0.1:3030",
    # api_key="sk-your-key",  # optional for managed tier
)

# In a LangChain chain:
# from langchain.chains import ConversationChain
# from langchain.chat_models import ChatOpenAI
# chain = ConversationChain(llm=ChatOpenAI(), memory=memory)
# chain.predict(input="Hello!")

# Async usage (FastAPI, Django async, LangChain 0.2+)
async def get_async_memory():
    from hipcortex import AsyncHipCortexClient
    from hipcortex.langchain_memory import AsyncHipCortexMemory
    client = AsyncHipCortexClient("http://127.0.0.1:3030")
    
    # Retrieve unified live beliefs for state and world predictions
    beliefs = await client.live_beliefs()
    print("Unified Live Beliefs:", beliefs)
    
    return AsyncHipCortexMemory(client=client, session_id="my-agent")
