"""HipCortex + DSPy — store compilation traces and optimization history.
Generated by: hipcortex install
"""
from hipcortex import HipCortexClient

client = HipCortexClient("http://127.0.0.1:3030")

def save_trace(program_name: str, trace: dict, score: float):
    """Store a DSPy optimization trace."""
    client.remember(
        f"DSPy trace for {program_name}: score={score:.3f} — {str(trace)[:200]}",
        actor=f"dspy-{program_name}",
        context="decision",
    )

def load_best_traces(program_name: str, limit: int = 5) -> list:
    """Retrieve top traces for a program."""
    return client.recall(f"DSPy trace {program_name} score", actor=f"dspy-{program_name}")
