#!/usr/bin/env bash
# HipCortex + n8n / Make.com / Zapier — HTTP Request examples
# Generated by: hipcortex install

HC="http://127.0.0.1:3030"

# Store memory (POST /memory/ingest — zero-config, auto-classifies)
curl -X POST "$HC/memory/ingest" \
  -H "Content-Type: application/json" \
  -d '{"text": "User Alice upgraded to Pro tier"}'

# Search memories (plain text response — easy to parse in n8n)
curl "$HC/memory/search-flat?query=Alice+plan&limit=5"

# In n8n: HTTP Request node → POST $HC/memory/ingest → body: {"text": "{{$json.text}}"}
# In Make.com: HTTP module → POST $HC/memory/ingest
# OpenAPI spec for auto-import: http://127.0.0.1:3030/openapi.json
