"""HipCortex + Pydantic AI — memory tools for AI agents.
Generated by: hipcortex install
Docs: https://github.com/farmountain/HipCortex
"""
from hipcortex import HipCortexClient
from pydantic_ai import Agent, Tool

client = HipCortexClient("http://127.0.0.1:3030")

def remember(text: str, actor: str = "default") -> str:
    """Store a memory. Use for decisions, findings, constraints."""
    result = client.remember(text, actor=actor)
    return f"Stored: {result.get('record_id', '?')}"

def recall(query: str, actor: str = "default") -> list:
    """Recall relevant memories matching a query."""
    return client.recall(query, actor=actor)

# Register as tools:
# agent = Agent("openai:gpt-4o", tools=[remember, recall])
