#!/usr/bin/env python3
"""
HipCortex Production Pair Setup — v3.8.0

Generates service configs for running hipcortex server + guided runner
as persistent background services (IDE-closed production pair).

Windows: NSSM (Non-Sucking Service Manager) commands
Linux:   systemd unit files in docs/service/

Usage:
  python scripts/production_pair_setup.py [--output-dir docs/service] [--actor my-runner] [--watch /var/hipcortex/watched.txt]
"""

import argparse
import os
import platform
import sys
from pathlib import Path

SYSTEMD_SERVER = """\
[Unit]
Description=HipCortex Cognitive Substrate Server
After=network.target

[Service]
Type=simple
WorkingDirectory={workdir}
ExecStart={cargo_run} --no-default-features --features petgraph_backend -- server
Restart=on-failure
RestartSec=3s
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
"""

SYSTEMD_RUNNER = """\
[Unit]
Description=HipCortex Guided Runner
After=network.target hipcortex-server.service
Wants=hipcortex-server.service

[Service]
Type=simple
WorkingDirectory={workdir}
ExecStart={python} {runner} --guided --goal-id {goal_id_placeholder} --watch {watch} --actor {actor} --server http://localhost:3030
Restart=on-failure
RestartSec=5s
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
"""

NSSM_SERVER = """\
rem HipCortex Server — install as Windows service with NSSM
nssm install hipcortex-server "{cargo}" run --no-default-features --features petgraph_backend -- server
nssm set hipcortex-server AppDirectory "{workdir}"
nssm set hipcortex-server AppStdout "{workdir}\\logs\\server.log"
nssm set hipcortex-server AppStderr "{workdir}\\logs\\server-err.log"
nssm set hipcortex-server Start SERVICE_AUTO_START
nssm start hipcortex-server
"""

NSSM_RUNNER = """\
rem HipCortex Guided Runner — install as Windows service with NSSM
rem Replace GOAL_ID_PLACEHOLDER with the actual goal UUID before running.
nssm install hipcortex-runner "{python}" "{runner}" --guided --goal-id GOAL_ID_PLACEHOLDER --watch "{watch}" --actor {actor} --server http://localhost:3030
nssm set hipcortex-runner AppDirectory "{workdir}"
nssm set hipcortex-runner AppStdout "{workdir}\\logs\\runner.log"
nssm set hipcortex-runner AppStderr "{workdir}\\logs\\runner-err.log"
nssm set hipcortex-runner AppDependencies hipcortex-server
nssm set hipcortex-runner Start SERVICE_AUTO_START
nssm start hipcortex-runner
"""


def main() -> None:
    p = argparse.ArgumentParser(description="HipCortex production pair setup v3.8.0")
    p.add_argument("--output-dir", default="docs/service")
    p.add_argument("--actor", default="prod-runner-1")
    p.add_argument("--watch", default="/var/hipcortex/watched.txt")
    args = p.parse_args()

    out = Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)

    workdir = str(Path.cwd())
    python = sys.executable
    runner = str(Path("scripts/hipcortex_runner.py"))
    cargo = "cargo"
    cargo_run = "cargo"

    is_windows = platform.system() == "Windows"

    if is_windows:
        server_file = out / "install_server.bat"
        runner_file = out / "install_runner.bat"
        server_file.write_text(NSSM_SERVER.format(
            cargo=cargo, workdir=workdir,
        ))
        runner_file.write_text(NSSM_RUNNER.format(
            python=python, runner=runner,
            watch=args.watch, actor=args.actor, workdir=workdir,
        ))
        print(f"[setup] Windows service scripts written:")
        print(f"  {server_file}  (run as Administrator)")
        print(f"  {runner_file}  (replace GOAL_ID_PLACEHOLDER first)")
    else:
        server_file = out / "hipcortex-server.service"
        runner_file = out / "hipcortex-runner.service"
        server_file.write_text(SYSTEMD_SERVER.format(
            workdir=workdir, cargo_run=cargo_run,
        ))
        runner_file.write_text(SYSTEMD_RUNNER.format(
            workdir=workdir, python=python, runner=runner,
            watch=args.watch, actor=args.actor,
            goal_id_placeholder="<GOAL_UUID>",
        ))
        print(f"[setup] systemd unit files written:")
        print(f"  {server_file}")
        print(f"  {runner_file}")
        print(f"")
        print(f"  sudo cp {server_file} /etc/systemd/system/")
        print(f"  sudo cp {runner_file} /etc/systemd/system/")
        print(f"  sudo systemctl daemon-reload")
        print(f"  sudo systemctl enable --now hipcortex-server hipcortex-runner")

    readme = out / "README.md"
    readme.write_text(f"""\
# HipCortex Production Pair Service Config

Generated by `scripts/production_pair_setup.py`.

See `docs/production_deployment.md` for the full IDE-closed production pair pattern.

## Files

| File | Purpose |
|------|---------|
| `{'install_server.bat' if is_windows else 'hipcortex-server.service'}` | HipCortex server (cognitive daemon) |
| `{'install_runner.bat' if is_windows else 'hipcortex-runner.service'}` | HipCortex guided runner (sensing daemon) |

## WAL persistence

The server writes a WAL on every mutation. Restart either service freely —
state survives. See `docs/production_deployment.md#restart-proof`.
""")
    print(f"  {readme}")
    print(f"[setup] Done. See docs/production_deployment.md for the full pattern.")


if __name__ == "__main__":
    main()
