mod aureus_bridge_tests;
mod integration_layer_tests;
mod memory_store_tests;
mod perception_adapter_tests;
mod snapshot_manager_tests;
mod symbolic_store_tests;
mod vision_encoder_tests;
mod temporal_indexer_tests;
mod procedural_cache_tests;
